// Mocks generated by Mockito 5.4.6 from annotations
// in boilerplate/test/unit/features/dog_image/dog_image_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:boilerplate/core/storage/database/app_database.dart' as _i6;
import 'package:boilerplate/features/dog_image/data/data_sources/dog_image_cache_data_source.dart'
    as _i5;
import 'package:boilerplate/features/dog_image/data/data_sources/dog_image_data_source.dart'
    as _i3;
import 'package:boilerplate/features/dog_image/data/models/dog_image_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDogImageModel_0 extends _i1.SmartFake implements _i2.DogImageModel {
  _FakeDogImageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DogImageDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDogImageDataSource extends _i1.Mock
    implements _i3.DogImageDataSource {
  MockDogImageDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DogImageModel> getRandom() =>
      (super.noSuchMethod(
            Invocation.method(#getRandom, []),
            returnValue: _i4.Future<_i2.DogImageModel>.value(
              _FakeDogImageModel_0(this, Invocation.method(#getRandom, [])),
            ),
          )
          as _i4.Future<_i2.DogImageModel>);
}

/// A class which mocks [DogImageCacheDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDogImageCacheDataSource extends _i1.Mock
    implements _i5.DogImageCacheDataSource {
  MockDogImageCacheDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> save(_i6.DogImagesCompanion? image) =>
      (super.noSuchMethod(
            Invocation.method(#save, [image]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.DogImage>> getSaved() =>
      (super.noSuchMethod(
            Invocation.method(#getSaved, []),
            returnValue: _i4.Future<List<_i6.DogImage>>.value(<_i6.DogImage>[]),
          )
          as _i4.Future<List<_i6.DogImage>>);

  @override
  _i4.Future<void> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
