// Mocks generated by Mockito 5.4.6 from annotations
// in boilerplate/test/unit/features/dog_image/dog_image_random_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:boilerplate/core/errors/failures.dart' as _i5;
import 'package:boilerplate/features/dog_image/domain/entities/dog_image_entity.dart'
    as _i6;
import 'package:boilerplate/features/dog_image/domain/use_cases/get_random_dog_image_use_case.dart'
    as _i2;
import 'package:boilerplate/features/dog_image/domain/use_cases/save_dog_image_use_case.dart'
    as _i8;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetRandomDogImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRandomDogImageUseCase extends _i1.Mock
    implements _i2.GetRandomDogImageUseCase {
  MockGetRandomDogImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.DogImageEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.DogImageEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.DogImageEntity>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.DogImageEntity>>);
}

/// A class which mocks [SaveDogImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveDogImageUseCase extends _i1.Mock
    implements _i8.SaveDogImageUseCase {
  MockSaveDogImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>> call(
    _i6.DogImageEntity? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i4.Unit>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>>);
}
