import 'package:envied/envied.dart';

part 'env.g.dart';

/// Compile-time configuration, generated by `envied` from one flavor's `.env`
/// file at code-generation time.
///
/// The default path is `.env.dev`, so a plain `dart run build_runner build`
/// works out of the box. Other flavors override the path through the envied
/// CLI define — enabled by `override: true` in `build.yaml` — which the
/// Makefile wraps:
///
/// ```sh
/// make env_production
/// # dart run build_runner build \
/// #   --define=envied_generator:envied=path=.env.production
/// ```
///
/// Only the selected flavor's values reach the binary; no other environment's
/// configuration is present to be read back out.
///
/// Fields marked `obfuscate: true` are XOR-scrambled at rest in `libapp.so`
/// and reassembled at runtime. That raises the effort of extracting them; it
/// is not encryption, and a value that must stay secret does not belong in a
/// client binary at all. Obfuscated fields must be declared `static final`,
/// not `static const` — the value is not a compile-time constant.
///
/// Nothing outside `config/env` reads [Env]. `AppConfig` is the facade.
///
/// Editing a `.env` file in place and rebuilding the same flavor can reuse a
/// cached result, because the path did not change. Run `make clean_gen` when
/// a value looks stale.
@Envied(path: '.env.dev', useConstantCase: true)
abstract class Env {
  @EnviedField(defaultValue: 'DEV')
  static const String environment = _Env.environment;

  @EnviedField()
  static const String baseUrl = _Env.baseUrl;

  @EnviedField(defaultValue: 10000)
  static const int connectTimeoutMs = _Env.connectTimeoutMs;

  @EnviedField(defaultValue: 30000)
  static const int receiveTimeoutMs = _Env.receiveTimeoutMs;

  @EnviedField(defaultValue: 30000)
  static const int sendTimeoutMs = _Env.sendTimeoutMs;

  @EnviedField(defaultValue: false)
  static const bool enableNetworkLog = _Env.enableNetworkLog;

  /// Secret — obfuscated at rest, hence `final` rather than `const`.
  @EnviedField(obfuscate: true, defaultValue: '')
  static final String apiKey = _Env.apiKey;

  @EnviedField(defaultValue: '')
  static const String validAndroidSignatures = _Env.validAndroidSignatures;

  @EnviedField(defaultValue: false)
  static const bool enableAntiProxy = _Env.enableAntiProxy;

  @EnviedField(defaultValue: '')
  static const String spkiSha256Hashes = _Env.spkiSha256Hashes;

  @EnviedField(defaultValue: '')
  static const String certificateSha256Fingerprints =
      _Env.certificateSha256Fingerprints;
}
