import java.util.Properties

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Loaded before the android block so both signingConfigs and buildTypes can
// see it. Null means the file is absent, which is the normal state for a
// fresh clone and for anyone who only builds debug.
val keystoreProperties: Properties? =
    rootProject.file("key.properties").takeIf { it.exists() }?.let { file ->
        Properties().apply { file.inputStream().use { load(it) } }
    }

android {
    namespace = "com.boilerplate.boilerplate"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // Product flavors override this per flavor; see flavorizr.gradle.kts.
        applicationId = "com.boilerplate.boilerplate"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    // Release signing is read from android/key.properties, which is NOT in
    // version control. Create it from key.properties.example alongside your
    // keystore, or have CI write it before the build.
    //
    // When the file is absent the release build falls back to the debug key so
    // `flutter run --release` still works locally. A debug-signed artifact
    // cannot be uploaded to Play, so the fallback cannot reach production by
    // accident — but it is announced rather than discovered at upload time.
    //
    // println, not logger.warn: `flutter build` filters Gradle's logger and
    // a warn-level line never reaches the terminal. This is configuration
    // time, so it prints on every build, which is why the wording does not
    // claim the current build is a release one.
    signingConfigs {
        if (keystoreProperties != null) {
            create("release") {
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
                storeFile = keystoreProperties.getProperty("storeFile")
                    ?.let { rootProject.file(it) }
                storePassword = keystoreProperties.getProperty("storePassword")
            }
        }
    }

    buildTypes {
        release {
            signingConfig = if (keystoreProperties != null) {
                signingConfigs.getByName("release")
            } else {
                println(
                    "WARNING: android/key.properties not found. Release " +
                        "builds will be signed with the DEBUG key and cannot " +
                        "be published. See android/key.properties.example."
                )
                signingConfigs.getByName("debug")
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----
